mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="polls/", permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User


class Question(models.Model):
    """
    A model representing a question for poll.

    Attributes:
        question_text: The text of the question.
        pub_date: The date and time when the question was published.
        end_date: The date and time when the question was ended.
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    end_date = models.DateTimeField('date ended', null=True, blank=True,
                                    default=None)

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def is_published(self):
        """
        The function checks if the publication date of an object is in
        the past.
        :return: a boolean value.
        """
        return self.pub_date <= timezone.now()

    def can_vote(self):
        """
        The function checks if a voting event is currently open for voting.
        :return: a boolean value.
        """
        if self.end_date is None:
            return self.is_published()
        else:
            return self.is_published() and self.end_date >= timezone.now()

    def was_published_recently(self):
        """
        The function checks if the publication date of an object is within the
        last 24 hours.
        :return: a boolean value.
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        """
        The function returns the question text as a string.
        :return: return the `question_text` attribute of the object.
        """
        return self.question_text


class Choice(models.Model):
    """
    A model representing a choice for a question in poll.

    Attributes:
        question: The question to which this choice belongs.
        choice_text: The text of the choice.
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    @property
    def votes(self):
        """
        The function returns the number of votes for a choice.
        :return: an integer value.
        """
        return self.vote_set.count()

    def __str__(self):
        """
        The above function returns the choice text as a string.
        :return: return the `choice_text` attribute of the object.
        """
        return self.choice_text

    def get_vote_count(self):
        """
        The function returns the number of votes for a choice.
        :return: an integer value.
        """
        return self.votes


class Vote(models.Model):
    """
    Record a vote for a choice in a particular question.
    """
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from .models import Question, Choice, Vote
from django.contrib.auth.decorators import login_required


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set
        to be published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            '-pub_date')


class DetailView(generic.DetailView):
    """View for displaying each question's detail.

    :param: Primary key of the question
    :return: Rendered template with question details
    """
    model = Question
    template_name = "polls/detail.html"
    object: Question

    def get_queryset(self):
        """Get questions that are already published.

        :return: Queryset of published questions
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get(self, request, *args, **kwargs):
        """Retrieve the specified question and display its details.

        :param request: The incoming request from the user.
        :param args: Additional arguments.
        :param kwargs: Keyword arguments, typically containing the question's
        primary key.
        :return: The rendered template showing the question's details.
        """
        try:
            self.object = get_object_or_404(Question, pk=kwargs["pk"])
        except Http404:
            messages.error(request,
                           f"Poll with ID {kwargs['pk']} is not found.")
            return redirect("polls:index")
        try:
            user_vote = self.object.choice_set.filter(
                vote__user=request.user).last()
        except TypeError:
            user_vote = None
        context = self.get_context_data(object=self.object,
                                        user_vote=user_vote)
        if not self.object.can_vote():
            messages.error(request,
                           f"The poll '{self.object}' "
                           f"has concluded and voting is closed.")
            return redirect("polls:index")
        return self.render_to_response(context)


class ResultsView(generic.DetailView):
    """
    The ResultsView class is a generic detail view in Python.
    """
    model = Question
    template_name = 'polls/results.html'

    def get(self, request, *args, **kwargs):
        """
        The `get` function retrieves a question object based on its
        primary key, checks if it is a future question, and displays
        an error message if it is not available for voting.

        :param request: The `request` parameter represents the HTTP request.
        :return: The code is returning a rendered HTML template with the
        question and a boolean value.
        """
        question = get_object_or_404(Question, pk=kwargs["pk"])
        is_future_question = not question.can_vote()
        if is_future_question:
            messages.error(request, "That poll is not available to vote.")
        return render(request, self.template_name, {"question": question,
                                                    "is_future_question":
                                                        is_future_question})


@login_required
def vote(request, question_id):
    """
    The function allows users to vote on a specific question and updates the
    vote count for the selected choice.

    :param request: The request object represents the HTTP request.
    :param question_id: The `question_id` parameter is the unique identifier.
    :return: an HTTP redirect response to the 'polls:results'.
    """
    question = get_object_or_404(Question, pk=question_id)
    if not question.can_vote():
        return redirect("login")  # Redirect to the login page if not logged in
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        messages.error(request, "Please select a choice!")
        return redirect("polls:detail", pk=question.id)
    this_user = request.user
    """if the user has a vote for this question, update the vote for
    selected_choice save it"""
    try:
        current_vote = Vote.objects.get(user=this_user,
                                        choice__question=question)
        current_vote.choice = selected_choice
    except Vote.DoesNotExist:
        current_vote = Vote(user=this_user, choice=selected_choice)
    current_vote.save()

    # Add a success message after saving the vote
    messages.success(request, f'Your vote for '
                              f'{selected_choice.choice_text} has been saved.')
    return HttpResponseRedirect(reverse(
        'polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poll Form</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <script>
        // Function to save the selected choice to localStorage

        document.addEventListener("DOMContentLoaded", function () {
            // Show the error message if it exists
            const errorDiv = document.getElementById("error");
            if (errorDiv && errorDiv.innerText.trim() !== "") {
                errorDiv.style.display = "block"; // Display the error message
                setTimeout(function () {
                    errorDiv.style.display = "none"; // Hide the error message after 2 seconds
                }, 2000); // 2000 milliseconds (2 seconds)
            }
        });
    </script>
</head>
<body class="detail">
    <form action="{% url 'polls:vote' question.id %}" method="post" class="detail">
        {% csrf_token %}
        <fieldset class="detail">
            <legend><h1 class="detail">{{ question.question_text }}</h1></legend>
            {% for choice in question.choice_set.all %}
                <div class="choice">
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" {% if user_vote and choice.id == user_vote.id %}checked="true"{% endif %}>
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                </div>
            {% endfor %}
        </fieldset>
        <div class="button-group">
        <input type="submit" value="Vote" class="button-vote">
        <a href="{% url 'polls:index' %}"><button type="button" class="button-vote">Back</button></a>
            <a href="{% url 'polls:results' question.id %}"><button type="button" class="button-vote">Results</button></a>
        </div>
        {% if user.is_authenticated %}
        <p class="welcome">Welcome back, {{ user.username.title }}</p><br/>
        <a class="login" href="{% url 'logout' %}">Log out</a><br/>
        {% else %}
        <a class="login" href="{% url 'login' %}"> Log in</a><br/>
        {% endif %}
        <div class="error-vote" id="error">
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <p style="color: #952323">{{ message }}</p>
                {% endif %}
            {% endfor %}
        </div>
    </form>
</body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>Ku Polls</title>
    <script>
    document.addEventListener("DOMContentLoaded", function () {
        const errorDiv = document.getElementById("error");
        if (errorDiv) {
            setTimeout(function () {
                errorDiv.style.display = "none";
            }, 2000); // 2000 milliseconds (2 seconds)
        }
    });
    </script>
</head>
<body class="index">
    <form class="index">
        <fieldset class="index">
            <legend><img src="{% static 'polls/images/KU.png' %}" alt="KU" class="ku"></legend>
                 <div class="container">
                    {% if latest_question_list %}
                        <div class="questions-list">
                            {% for question in latest_question_list %}
                                <div class="question-item">
                                    <a class="no-hover">{{ question.question_text }}</a><br>
                                    <span class="vote-status">
                                        {% if question.can_vote %}
                                            Status: <img src="{% static 'polls/images/check.png' %}" class="check">
                                        {% else %}
                                            Status: <img src="{% static 'polls/images/cross.png' %}" class="check">
                                        {% endif %}
                                    </span>
                                    <div class="actions">
                                        <a class="button-views" href="{% url 'polls:detail' question.id %}">Vote</a>
                                        <a class="button-results" href="{% url 'polls:results' question.id %}">Results</a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p>No polls are available.</p>
                    {% endif %}
                </div>
        </fieldset>
                    {% if user.is_authenticated %}
                    <p class="welcome">Welcome back, {{ user.username.title }}</p><br/>
                    <a class="login" href="{% url 'logout' %}">Log out</a>
                {% else %}
                    <a class="login" href="{% url 'login' %}"> Log in</a>
                {% endif %}
        {% if messages %}
            <ul>
                <div id="error" class="error" style="color: #C70039">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </div>
            </ul>
        {% endif %}
    </form>
</body>
</html>

polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>Poll Results</title>
    <style>
        /* Define the fixed size for the canvas */
        #pollResultsChart {
            width: 400px; /* Adjust to your desired width */
            height: 400px; /* Adjust to your desired height */
            margin: 0 auto; /* Center the canvas horizontally */
            display: block; /* Ensure it's a block element for margin:auto to work */
        }
    </style>
</head>
<body class="results">
    <form class="results">
        <fieldset class="results">
            <legend><h1 class="results">{{ question.question_text }}</h1></legend>
            <main>
                <canvas id="pollResultsChart"></canvas>
                {% if messages %}
                    <div class="messages">
                {% for message in messages %}
                    <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
                     </div>
                {% endif %}
                <div id="totalVotes"></div>
                <div id="buttonContainer">
                    <a class="button-home" href="{% url 'polls:index' %}">Back to home</a>
                </div>
            </main>
        </fieldset>
        {% if user.is_authenticated %}
        <p class="welcome">Welcome back, {{ user.username.title }}</p><br/>
        <a class="login" href="{% url 'logout' %}">Log out</a><br/>
        {% else %}
        <a class="login" href="{% url 'login' %}"> Log in</a><br/>
        {% endif %}
    </form>

<script>
    // Get the poll data from Django template variables
    let labels = [{% for choice in question.choice_set.all %}"{{ choice.choice_text }}",{% endfor %}];
    let votes = [{% for choice in question.choice_set.all %}{{ choice.votes }},{% endfor %}];

    // Calculate the total votes
    let totalVotes = votes.reduce((a, b) => a + b, 0);

    // Update the labels to include vote count and total vote count
    for (let i = 0; i < labels.length; i++) {
        labels[i] += ` (${votes[i]} votes)`;
    }

    // Display the total vote count
    document.getElementById('totalVotes').textContent = `Total Votes: ${totalVotes}`;

    let pollData = {
        labels: labels,
        datasets: [{
            data: votes,
            backgroundColor: [
                'rgba(255, 99, 132, 0.5)',
                'rgba(54, 162, 235, 0.5)',
                'rgba(255, 206, 86, 0.5)',
                'rgba(75, 192, 192, 0.5)',
                'rgba(153, 102, 255, 0.5)',
                'rgba(255, 159, 64, 0.5)'
                // Add more colors as needed
            ],
        }],
    };

    // Get the canvas element
    let ctx = document.getElementById('pollResultsChart').getContext('2d');

    // Create the pie chart with custom font for labels and text color
    let pollResultsChart = new Chart(ctx, {
        type: 'pie',
        data: pollData,
        options: {
            responsive: false, // Disable responsive resizing
            plugins: {
                legend: {
                    labels: {
                        font: {
                            family: 'Mulish', // Set the font family for labels
                        },
                        color: '#016A70', // Set the font color
                    },
                },
            },
        },
    });
</script>
</body>
</html>